name: No logs for you
on:
  workflow_run:
    workflows: ["Chall 2 🔒"]
    types:
      - completed

permissions:
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Cleanup your mess
      env:
        ID: ${{ github.event.comment.id }}
        PAYLOAD: ${{ github.event.issue.body }}
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "toto"
